stm_bm(["menu39ef",660,"","blank.gif",0,"","",0,0,250,0,1000,1,0,0,"","",0,0,1,1,"default","hand",""],this);
stm_bp("p0",[1,4,0,0,2,2,0,7,100,"",-2,"",-2,50,2,3,"#999999","#FFFFFF","",3,1,1,"#999999"]);
stm_ai("p0i0",[0,"Inicio","","",-1,-1,0,"http://www.sanrafaellate.com.ar/","_self","","Ir a la pagina principal","","",0,0,0,"","",0,0,0,0,1,"#FFFFFF",0,"#DFDFDF",0,"","",3,3,1,1,"#FFFFFF","#666666","#333333","#333333","9pt Verdana","9pt Verdana",0,0]);
stm_aix("p0i1","p0i0",[0,"Fotos","","",-1,-1,0,"http://www.sanrafaellate.com.ar/GaleriasdeFotos.htm","_self","","Conoce los espectaculares paisajes de San Rafael "]);
stm_aix("p0i2","p0i0",[0,"Clasificados","","",-1,-1,0,"http://www.sanrafaellate.com.ar/Clasificados/Clasificados.htm","_self","","buscas laburo, queres vender o comprar.. o queres publicar algo aprovecha es totalmente GRATIS!!"]);
stm_aix("p0i3","p0i0",[0,"Informacion","","",-1,-1,0,"","_self","","","","",0,0,0,"arrow_gray.gif","arrow_r.gif",7,7]);
stm_bpx("p1","p0",[1,2,-2,0,3,1,0,0,91]);
stm_aix("p1i0","p0i0",[0,"San Rafael","","",-1,-1,0,"http://www.sanrafaellate.com.ar/san%20rafael/San%20Rafael.htm","_self","","Conozca San Rafael- Reseña Historica"]);
stm_aix("p1i1","p0i0",[0,"Circiutos Turisticos","","",-1,-1,0,"http://www.sanrafaellate.com.ar/circuitos%20turisticos/circuitos%20turisticos.htm","_self","","Todos los circuitos turisticos que podes visitar en nuestra ciudad, valle grande , nihuil, alta montaña, etc"]);
stm_aix("p1i2","p0i0",[0,"Mapas","","",-1,-1,0,"http://www.sanrafaellate.com.ar/mapas.htm","_self","","mapas satelitales,mapas de rutas de argentina, mendoza, como tabien plano de la ciudad de san rafael"]);
stm_aix("p1i3","p0i0",[0,"Agenda","","",-1,-1,0,"http:/www.sanrafaellate.com.ar/Agenda.htm","_self","","La Agenda de san rafael "]);
stm_ep();
stm_aix("p0i4","p0i0",[0,"Alojamiento","","",-1,-1,0,"http://www.sanrafaellate.com.ar/alojamiento/Alojamientos.HTM","_self","","Compltisima guia de hoteles, cabañas, complejos, camping, etc"]);
stm_aix("p0i5","p0i0",[0,"Gastronomia","","",-1,-1,0,"http://www.sanrafaellate.com.ar/gastronomia/gastronomia.HTM","_self","","Un delisiosa guia de restaurantes, parrilas, etc"]);
stm_aix("p0i6","p0i3",[0,"Esparacimiento"]);
stm_bpx("p2","p1",[]);
stm_aix("p2i0","p0i0",[0,"Regionales","","",-1,-1,0,"http://www.sanrafaellate.com.ar/entretenimientos/regionales.HTM","_self","","Para llevarte recuerdos de San Rafael visita algunos de estos lugares"]);
stm_aix("p2i1","p0i0",[0,"Entretenimientos","","",-1,-1,0,"http://www.sanrafaellate.com.ar/entretenimientos/entretenimiento.HTM","_self","","los lugares a visitar para tu diversion, Casinos, Cines, Confiterias, Museos, etc "]);
stm_aix("p2i2","p0i0",[0,"Deportes","","",-1,-1,0,"http://www.sanrafaellate.com.ar/entretenimientos/Deportes.HTM","_self","","Compencias, Golf, futbol, tenis,paddle, etc."]);
stm_ep();
stm_aix("p0i7","p0i3",[0,"Servicios"]);
stm_bpx("p3","p1",[]);
stm_aix("p3i0","p0i0",[0,"Agencias de viajes","","",-1,-1,0,"http://www.sanrafaellate.com.ar/servicios/agencias%20de%20viajes.htm","_self","","Todas la agencia viajes de San Rafael , aventura, turismo, contratados"]);
stm_aix("p3i1","p0i0",[0,"Estaciones de GNC","","",-1,-1,0,"http://www.sanrafaellate.com.ar/servicios/Estanciones%20servicios%20GNC.HTM","_self","","Saber donde abastecerse siempre es importante...tenes a tu alcance todas las estaciones de serviucio de San Rafael"]);
stm_ep();
stm_aix("p0i8","p0i0",[0,"Transporte","","",-1,-1,0,"http://www.sanrafaellate.com.ar/transporte/transportes.htm","_self","","Encontra todos los  trasportes para tus viajes, aereos, larga distancia, taxis , Renta car,etc... para llegar salir o recorrer San Rafael"]);
stm_aix("p0i9","p0i3",[0,"La Noche ","","",-1,-1,0,"http://www.sanrafaellate.com.ar/lanoche/Lanoche.htm","_self","","Conoce la noche san rafaelina ...boliches bares espectaculos, etc"]);
stm_bpx("p4","p1",[]);
stm_aix("p4i0","p0i0",[0,"Boliches y bares","","",-1,-1,0,"http://www.sanrafaellate.com.ar/lanoche/bolichesybares.HTM","_self","","Conoce los boliche y pubs de onda en San Rafael"]);
stm_aix("p4i1","p0i0",[0,"Espectaculos","","",-1,-1,0,"http://www.sanrafaellate.com.ar/lanoche/Espectaculos.htm","_self","","Todos los espectaculos de San Rafael , Teatro, musica, show , ect"]);
stm_ep();
stm_aix("p0i10","p0i0",[0,"Vinos","","",-1,-1,0,"http://www.sanrafaellate.com.ar/vinos/vinos.htm","_self","","Para los amantes del vino ponemos a su disposicion una guia  Bodegas Wine Bar y  Vinotecas"]);
stm_aix("p0i11","p0i0",[0,"Links","","",-1,-1,0,"http://www.sanrafaellate.com.ar/link.htm","_self","","Sitios web de interes"]);
stm_ep();
stm_em();
